source 'http://rubygems.org'
source 'http://gemcutter.org'

gem 'rails', '5.2.4.3'
gem 'mongoid', '6.0.0'
gem 'bson_ext'
gem 'yajl-ruby'
gem 'will_paginate'
gem 'rack-ssl'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'validate_url', '0.1.6'
gem 'email_validator'
gem 'chronic'
gem 'jquery-rails', '>= 1.0.1'

group :development, :test do
  gem 'rspec-rails', '2.8.0'
  gem 'cucumber-rails'
  gem 'steak'
  gem 'capybara'
  gem 'selenium-client'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'shoulda'
  gem 'factory_girl_rails', '1.1.0'
  gem 'webrat'
  gem 'autotest'
  gem 'autotest-growl'
  gem 'database_cleaner'
  gem 'fuubar'
  gem 'watchr'
  gem 'delorean'
  gem 'rspec-set'
end
