source 'http://rubygems.org'
source 'http://gemcutter.org'

gem 'rails', '5.0.0'
gem 'mongoid', '2.0.0.beta.20'
gem 'bson_ext'
gem 'yajl-ruby'
gem 'will_paginate'
gem 'rack-ssl', '>= 1.3.2'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'validate_url', '0.1.6'
gem 'email_validator'
gem 'chronic'
gem 'jquery-rails', '>= 4.4.0'

group :development, :test do
  gem 'rspec-rails', '2.8.0'
  gem 'cucumber-rails', '>= 0.4.1'
  gem 'steak'
  gem 'capybara', '>= 0.4.1.2'
  gem 'selenium-client'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'shoulda'
  gem 'factory_girl_rails', '1.1.0'
  gem 'webrat', '>= 0.7.3'
  gem 'autotest'
  gem 'autotest-growl'
  gem 'database_cleaner'
  gem 'fuubar'
  gem 'watchr'
  gem 'delorean'
  gem 'rspec-set'
end
